uiroute.config(function ($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/Index');
    $stateProvider
        // State managing  
        .state('Index', {
            url: '/Index',
            templateUrl: '/App/Test/Index.html',
            controller: 'IndexController'
        }).state('UserFilterSearch', {
            url: '/UserFilterSearch',
            templateUrl: '/App/Test/UserFilterSearch.html',
            controller: 'FilterSearchController'
        }).state('Login', {
            url: '/Login',
            templateUrl: '/App/Client/Login.html',
            controller: 'LoginController'
        })
        .state('Register', {
            url: '/Register',
            templateUrl: '/App/Client/Register.html',
            controller: 'RegisterController'
        })
        .state('Search', {
            url: '/Search',
            templateUrl: '/App/Client/Search.html',
            controller: 'SearchController'
        }).state('FilterSearch', {
            url: '/FilterSearch',
            templateUrl: '/App/Client/FilterSearch.html',
            controller: 'FilterSearchController'
        }).state('Traveller', {
            url: '/Traveller',
            templateUrl: '/App/Client/Traveller.html',
            controller: 'TravellerController'
        }).state('Extras', {
            url: '/Extras',
            templateUrl: '/App/Client/Extras.html',
            controller: 'ExtrasController'
        })//hotel
        .state('UserHotelFilterSearch', {
            url: '/UserHotelFilterSearch',
            templateUrl: '/App/Test/UserHotelFilterSearch.html',
            controller: 'UserHotelFilterSearch'
        }).state('UserSelectRoom', {
            url: '/UserSelectRoom',
            templateUrl: '/App/Test/UserSelectRoom.html',
            controller: 'UserSelectRoom'
        }).state('HotelIndex', {
            url: '/HotelIndex',
            templateUrl: '/App/Test/HotelIndex.html',
            controller: 'HotelIndexController'
        }).state('HotelFilterSearch', {
            url: '/HotelFilterSearch',
            templateUrl: '/App/Hotel/HotelFilterSearch.html',
            controller: 'HotelFilterSearch'
        }).state('HotelSearch', {
            url: '/HotelSearch',
            templateUrl: '/App/Hotel/HotelSearch.html',
            controller: 'HotelSearch'
        }).state('SelectRoom', {
            url: '/SelectRoom',
            templateUrl: '/App/Hotel/SelectRoom.html',
            controller: 'SelectRoom'
        }).state('Partner', {
            url: '/Partner',
            templateUrl: '/App/Hotel/Partner.html',
            controller: 'PartnerController'
        }).state('CarIndex', {
            url: '/CarIndex',
            templateUrl: '/App/Car/CarIndex.html',
            controller: 'CarIndexController'
        }).state('UserFilterCar', {
            url: '/UserFilterCar',
            templateUrl: '/App/Test/UserFilterCar.html',
            controller: 'FilterCarController'
        }).state('CarRegister', {
            url: '/CarRegister',
            templateUrl: '/App/Car/CarRegister.html',
            controller: 'CarRegister'
        }).state('CarLogin', {
            url: '/CarLogin',
            templateUrl: '/App/Car/CarLogin.html',
            controller: 'CarLogin'
        }).state('CarSearch', {
            url: '/CarSearch',
            templateUrl: '/App/Car/CarSearch.html',
            controller: 'CarSearch'
        }).state('FilterCar', {
            url: '/FilterCar',
            templateUrl: '/App/Car/FilterCar.html',
            controller: 'FilterCarController'
        }).state('Driver', {
            url: '/Driver',
            templateUrl: '/App/Car/Driver.html',
            controller: 'Driver'
        }).state('HotelLogin', {
            url: '/HotelLogin',
            templateUrl: '/App/Hotel/HotelLogin.html',
            controller: 'HotelLogin'
        }).state('HotelRegister', {
            url: '/HotelRegister',
            templateUrl: '/App/Hotel/HotelRegister.html',
            controller: 'HotelRegister'
        }).state('AdminRegistration', {
            url: '/AdminRegistration',
            templateUrl: '/App/Administrator/AdminRegistration.html',
            controller: 'AdminRegisterController'
        }).state('AdminLogin', {
            url: '/AdminLogin',
            templateUrl: '/App/Administrator/AdminLogin.html',
            controller: 'AdminLoginController'
        }).state('AdminDashBoard', {
            url: '/AdminDashBoard',
            templateUrl: '/App/Administrator/AdminDashBoard.html',
            controller: 'AdminDashboard'
        })//Admin Module
        .state('Client', {
            url: '/Client',
            templateUrl: '/App/Administrator/Client.html',
            controller: 'ClientController'
        }).state('Flight', {
            url: '/Flight',
            templateUrl: '/App/Administrator/Flight.html',
            controller: 'AdminFlightController'
        }).state('Hotel', {
            url: '/Hotel',
            templateUrl: '/App/Administrator/Hotel.html',
            controller: 'AdminHotelController'
        }).state('Car', {
            url: '/Car',
            templateUrl: '/App/Administrator/Car.html',
            controller: 'AdminCarController'
        }).state('ClientDashboard', {
            url: '/ClientDashboard',
            templateUrl: '/App/Dashboard/ClientDashboard.html',
            controller: 'Dashboard'
        }).state('Booking', {
            url: '/Booking',
            templateUrl: '/App/Dashboard/Booking.html',
            controller: 'Booking'
        }).state('Additional', {
            url: '/Additional',
            templateUrl: '/App/Dashboard/Additional.html',
            controller: 'Additional'
        }).state('FlightPayment', {
            url: '/FlightPayment',
            templateUrl: '/App/Client/FlightPayment.html',
            controller: 'FlightPayment'
        }).state('CarPayment', {
            url: '/CarPayment',
            templateUrl: '/App/Car/CarPayment.html',
            controller: 'CarPayment'
        }).state('HotelPayment', {
            url: '/HotelPayment',
            templateUrl: '/App/Hotel/HotelPayment.html',
            controller: 'HotelPayment'
        }).state('TestingImage', {
            url: '/TestingImage',
            templateUrl: '/App/Hotel/TestingImage.html',
            controller: 'fupController'
        }).state('Bisho', {
            url: '/Bisho',
            templateUrl: '/App/Administrator/Bisho.html',
            controller: 'Bisho'
        }).state('UserReturn', {
            url: '/UserReturn',
            templateUrl: '/App/Test/UserReturn.html',
            controller: 'Return'
        }).state('Return', {
            url: '/Return',
            templateUrl: '/App/Client/Return.html',
            controller: 'ClientReturn'
        });
});

