//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Client_Car = new HashSet<Client_Car>();
        }
    
        public int CarId { get; set; }
        public string Name { get; set; }
        public string Mileage { get; set; }
        public Nullable<double> Price { get; set; }
        public string SpecialOffer { get; set; }
        public string CarSpecifications { get; set; }
        public string Transmission { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> TotalCars { get; set; }
        public Nullable<int> CarsLeft { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Car> Client_Car { get; set; }
    }
}
