//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Rooms = new HashSet<Room>();
            this.Client_Hotel = new HashSet<Client_Hotel>();
        }
    
        public int HotelID { get; set; }
        public string Name { get; set; }
        public string TelNumber { get; set; }
        public Nullable<int> StarRating { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> RoomsLeft { get; set; }
    
        public virtual Residence Residence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Hotel> Client_Hotel { get; set; }
    }
}
