//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BootCampEntities : DbContext
    {
        public BootCampEntities()
            : base("name=BootCampEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Residence> Residences { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Traveller> Travellers { get; set; }
        public virtual DbSet<Client_Car> Client_Car { get; set; }
        public virtual DbSet<Client_Flight> Client_Flight { get; set; }
        public virtual DbSet<Client_Hotel> Client_Hotel { get; set; }
        public virtual DbSet<CarPayment> CarPayments { get; set; }
        public virtual DbSet<FlightPayment> FlightPayments { get; set; }
        public virtual DbSet<HotelPayment> HotelPayments { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
    }
}
