//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residence()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int LocationID { get; set; }
        public string StreetName { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Country { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
        public virtual Administrator Administrator { get; set; }
    }
}
